"""Default Load Metadata values applied before saved JSON overrides."""

from __future__ import annotations

from typing import Any

import gradio as gr

from acestep.model_downloader import (
    DEFAULT_LM_MODEL,
    DEFAULT_TURBO_DIT_MODEL,
    DEFAULT_VAE_VARIANT,
)

from .audio_format_options import (
    DEFAULT_AUDIO_FORMAT,
    DEFAULT_EXTRACT_AUDIO_FORMAT,
    DEFAULT_MP3_BITRATE,
)
from .metadata_restore_settings import audio_processing_ui_values, sam_audio_ui_values


def default_metadata_values() -> dict[str, Any]:
    """Return default UI values used before applying saved metadata."""

    values: dict[str, Any] = {
        "generation_mode": "Custom",
        "task_type": "text2music",
        "captions": "",
        "lyrics": "",
        "vocal_language": "unknown",
        "bpm": None,
        "key_scale": "",
        "time_signature": "",
        "audio_duration": -1,
        "batch_size_input": 1,
        "inference_steps": 8,
        "guidance_scale": 7.0,
        "seed": "-1",
        "random_seed_checkbox": False,
        "reference_audio": None,
        "src_audio": None,
        "use_adg": False,
        "cfg_interval_start": 0.0,
        "cfg_interval_end": 1.0,
        "shift": 3.0,
        "infer_method": "ode",
        "sampler_mode": "euler",
        "velocity_norm_threshold": 0.0,
        "velocity_ema_factor": 0.0,
        "dcw_enabled": True,
        "dcw_mode": "double",
        "dcw_scaler": 0.02,
        "dcw_high_scaler": 0.06,
        "dcw_wavelet": "haar",
        "custom_timesteps": "",
        "audio_format": DEFAULT_AUDIO_FORMAT,
        "mp3_controls_row": gr.update(visible=True),
        "mp3_bitrate": DEFAULT_MP3_BITRATE,
        "mp3_sample_rate": 48000,
        "lm_temperature": 0.85,
        "lm_cfg_scale": 2.0,
        "lm_top_k": 0,
        "lm_top_p": 0.9,
        "lm_negative_prompt": "NO USER INPUT",
        "use_cot_metas": True,
        "use_cot_caption": True,
        "use_cot_language": True,
        "audio_cover_strength": 1.0,
        "cover_noise_strength": 0.0,
        "think_checkbox": True,
        "text2music_audio_code_string": "",
        "repainting_start": 0.0,
        "repainting_end": -1,
        "track_name": None,
        "extract_all_stems": False,
        "extract_output_format": DEFAULT_EXTRACT_AUDIO_FORMAT,
        "complete_track_classes": [],
        "instrumental_checkbox": False,
        "repaint_dont_switch_with_lyrics": False,
        "retake_variance": 0.0,
        "retake_seed": "",
        "flow_edit_morph": False,
        "flow_edit_source_caption": "",
        "flow_edit_source_lyrics": "",
        "flow_edit_n_min": 0.0,
        "flow_edit_n_max": 1.0,
        "flow_edit_n_avg": 1,
        "enable_normalization": True,
        "normalization_db": -1.0,
        "fade_in_duration": 0.0,
        "fade_out_duration": 0.0,
        "latent_shift": 0.0,
        "latent_rescale": 1.0,
        "no_fsq": False,
        "constrained_decoding_debug": False,
        "allow_lm_batch": True,
        "auto_score": False,
        "auto_lrc": False,
        "score_scale": 0.5,
        "lm_batch_chunk_size": 8,
        "generate_lm_audio_codes": True,
        "extract_trim_empty_output": False,
        "extract_trim_threshold_db": -40.0,
        "config_path": DEFAULT_TURBO_DIT_MODEL,
        "device": "auto",
        "vae_checkpoint": DEFAULT_VAE_VARIANT,
        "lm_model_path": DEFAULT_LM_MODEL,
        "backend_dropdown": "pt",
        "init_llm_checkbox": False,
        "lm_use_legacy_cfg_prompt": False,
        "use_flash_attention_checkbox": True,
        "offload_to_cpu_checkbox": False,
        "offload_dit_to_cpu_checkbox": False,
        "compile_model_checkbox": False,
        "quantization_checkbox": "none",
        "mlx_dit_checkbox": False,
        "mlx_vae_chunk_size": 64,
        "lora_path": "",
        "lora_dropdown": "",
        "use_lora_checkbox": False,
        "lora_scale_slider": 1.0,
        "subprocess_mode_checkbox": False,
        "ap_run_subprocess": True,
        "ap_disable_upload_preview": False,
    }
    values.update(audio_processing_ui_values({}))
    values.update(sam_audio_ui_values({}))
    return values
