"""Default values for premium custom-preset schema extensions."""

from __future__ import annotations

from typing import Any

from acestep.constants import DEFAULT_DIT_INSTRUCTION
from acestep.model_downloader import DEFAULT_TURBO_DIT_MODEL, DEFAULT_VAE_VARIANT


ADDITIONAL_DEFAULT_PRESET_VALUES: dict[str, Any] = {
    "vae_checkpoint": DEFAULT_VAE_VARIANT,
    "lm_use_legacy_cfg_prompt": False,
    "lm_codes_audio_upload": None,
    "no_fsq": False,
    "task_type": "text2music",
    "instruction_display_gen": DEFAULT_DIT_INSTRUCTION,
    "retake_enabled": False,
    "retake_variance": 0.0,
    "retake_seed": "",
    "flow_edit_morph": False,
    "flow_edit_source_caption": "",
    "flow_edit_source_lyrics": "",
    "flow_edit_n_min": 0.0,
    "flow_edit_n_max": 1.0,
    "flow_edit_n_avg": 1,
    "dataset_type": "train",
    "dataset_import_path": "",
    "search_type": "random",
    "search_value": "",
    "use_src_checkbox": True,
    "load_json_path": "",
    "audio_directory": "",
    "save_path": "./datasets/my_lora_dataset.json",
    "load_existing_dataset_path": "",
    "preprocess_mode": "LoRA",
    "preprocess_debug_text": False,
    "preprocess_output_dir": "./datasets/preprocessed_tensors",
    "preprocess_subprocess": True,
    "training_tensor_dir": "./datasets/preprocessed_tensors",
    "lora_model_config": DEFAULT_TURBO_DIT_MODEL,
    "lora_vram_preset": "24GB+",
    "lora_adapter_type": "lora",
    "lora_name": "",
    "lora_rank": 128,
    "lora_alpha": 128,
    "lora_dropout": 0.0,
    "lora_target_mlp": False,
    "learning_rate": 3e-4,
    "train_epochs": 100,
    "train_batch_size": 1,
    "gradient_accumulation": 1,
    "save_every_n_epochs": 10,
    "lora_save_best": True,
    "lora_save_best_after": 10,
    "lora_save_best_smoothing_window": 5,
    "lora_save_best_min_delta": 0.001,
    "training_shift": 3.0,
    "training_num_inference_steps": 8,
    "training_seed": 42,
    "lora_optimizer_type": "adamw",
    "lora_scheduler_type": "constant",
    "lora_timestep_mode": "continuous",
    "lora_adaptive_timestep_ratio": 0.0,
    "lora_validation_split_percent": 0,
    "resume_checkpoint_dir": "",
    "training_subprocess": True,
    "lora_gradient_checkpointing": True,
    "lora_activation_cpu_offload": False,
    "lora_offload_non_decoder": True,
    "lora_keep_frozen_bf16": False,
    "lora_base_quantization": "Disabled",
    "lora_empty_cache_every_n_steps": 0,
    "lora_sample_enabled": False,
    "lora_sample_every_n_epochs": 10,
    "lora_sample_seed": 42,
    "lora_sample_offload_training_model": False,
    "lora_sample_offload_generation": True,
    "simple_create_vocal_gender": "male",
    "simple_create_cover_image": None,
    "simple_create_video_resolution": "1080p",
    "lokr_training_tensor_dir": "./datasets/preprocessed_tensors",
    "lokr_linear_dim": 64,
    "lokr_linear_alpha": 128,
    "lokr_factor": -1,
    "lokr_decompose_both": False,
    "lokr_use_tucker": False,
    "lokr_use_scalar": False,
    "lokr_weight_decompose": True,
    "lokr_learning_rate": 1e-3,
    "lokr_train_epochs": 500,
    "lokr_train_batch_size": 1,
    "lokr_gradient_accumulation": 4,
    "lokr_save_every_n_epochs": 10,
    "lokr_training_shift": 3.0,
    "lokr_training_num_inference_steps": 8,
    "lokr_training_seed": 42,
    "lokr_output_dir": "./lokr_output",
    "lokr_export_path": "./lokr_output/final_lokr",
    "lokr_export_epoch": "Latest (auto)",
    "batch_input_folder": "",
    "batch_output_folder": "",
    "batch_auto_improve_lyrics": False,
    "batch_auto_improve_style": False,
}
