"""Default values for premium custom-preset schema extensions."""

from __future__ import annotations

from typing import Any

from acestep.audio_processing.auto_editor_workflow import (
    AUTO_EDITOR_WORKFLOW_EXPORT_KEY,
    AUTO_EDITOR_WORKFLOW_EXPORT_NONE,
)
from acestep.audio_processing.presets import DEFAULT_STAGE_VALUES, STAGE_KEYS
from acestep.audio_processing.settings import (
    AUDIO_PROCESSING_DEFAULT_TRIM_MARGIN_SECONDS,
    AUDIO_PROCESSING_DEFAULT_TRIM_MINCLIP,
    AUDIO_PROCESSING_DEFAULT_TRIM_MINCUT,
    AUDIO_PROCESSING_DEFAULT_TRIM_THRESHOLD_DB,
)
from acestep.audio_processing.video_reencode_settings import (
    DEFAULT_VIDEO_AUDIO_BITRATE,
    DEFAULT_VIDEO_AUDIO_CODEC,
    DEFAULT_VIDEO_AUTO_QUALITY,
    DEFAULT_VIDEO_BITRATE,
    DEFAULT_VIDEO_CODEC,
    DEFAULT_VIDEO_CRF,
    DEFAULT_VIDEO_PRESET,
)
from acestep.constants import DEFAULT_DIT_INSTRUCTION
from acestep.model_downloader import DEFAULT_TURBO_DIT_MODEL, DEFAULT_VAE_VARIANT
from acestep.sam_audio_segment.settings import SAM_AUDIO_DEFAULT_TRIM_THRESHOLD_DB
from acestep.sam_audio_segment.vram_presets import (
    default_sam_vram_preset_name,
    get_sam_vram_preset,
)

_DEFAULT_SAM_VRAM_PRESET = default_sam_vram_preset_name()
_DEFAULT_SAM_VRAM_VALUES = get_sam_vram_preset(_DEFAULT_SAM_VRAM_PRESET)

ADDITIONAL_DEFAULT_PRESET_VALUES: dict[str, Any] = {
    "vae_checkpoint": DEFAULT_VAE_VARIANT,
    "lm_use_legacy_cfg_prompt": False,
    "lm_codes_audio_upload": None,
    "no_fsq": False,
    "task_type": "text2music",
    "instruction_display_gen": DEFAULT_DIT_INSTRUCTION,
    "retake_enabled": False,
    "retake_variance": 0.0,
    "retake_seed": "",
    "extract_output_format": "mp3",
    "flow_edit_morph": False,
    "flow_edit_source_caption": "",
    "flow_edit_source_lyrics": "",
    "flow_edit_n_min": 0.0,
    "flow_edit_n_max": 1.0,
    "flow_edit_n_avg": 1,
    "dataset_type": "train",
    "dataset_import_path": "",
    "search_type": "random",
    "search_value": "",
    "use_src_checkbox": True,
    "load_json_path": "",
    "audio_directory": "",
    "save_path": "./datasets/my_lora_dataset.json",
    "load_existing_dataset_path": "",
    "preprocess_mode": "LoRA",
    "preprocess_debug_text": False,
    "preprocess_output_dir": "./datasets/preprocessed_tensors",
    "preprocess_subprocess": True,
    "training_tensor_dir": "./datasets/preprocessed_tensors",
    "lora_model_config": DEFAULT_TURBO_DIT_MODEL,
    "lora_vram_preset": "24GB+",
    "lora_adapter_type": "lora",
    "lora_name": "",
    "lora_rank": 128,
    "lora_alpha": 128,
    "lora_dropout": 0.0,
    "lora_target_mlp": False,
    "learning_rate": 3e-4,
    "train_epochs": 100,
    "train_batch_size": 1,
    "gradient_accumulation": 1,
    "save_every_n_epochs": 10,
    "lora_save_best": True,
    "lora_save_best_after": 10,
    "lora_save_best_smoothing_window": 5,
    "lora_save_best_min_delta": 0.001,
    "training_shift": 3.0,
    "training_num_inference_steps": 8,
    "training_seed": 42,
    "lora_optimizer_type": "adamw",
    "lora_scheduler_type": "constant",
    "lora_timestep_mode": "continuous",
    "lora_adaptive_timestep_ratio": 0.0,
    "lora_validation_split_percent": 0,
    "resume_checkpoint_dir": "",
    "training_subprocess": True,
    "lora_gradient_checkpointing": True,
    "lora_activation_cpu_offload": False,
    "lora_offload_non_decoder": True,
    "lora_keep_frozen_bf16": False,
    "lora_compile_model": False,
    "lora_base_quantization": "Disabled",
    "lora_empty_cache_every_n_steps": 0,
    "lora_sample_enabled": False,
    "lora_sample_every_n_epochs": 10,
    "lora_sample_seed": 42,
    "lora_sample_offload_training_model": False,
    "lora_sample_offload_generation": True,
    "simple_create_vocal_gender": "male",
    "simple_create_cover_image": None,
    "simple_create_video_resolution": "1080p",
    "lokr_training_tensor_dir": "./datasets/preprocessed_tensors",
    "lokr_linear_dim": 64,
    "lokr_linear_alpha": 128,
    "lokr_factor": -1,
    "lokr_decompose_both": False,
    "lokr_use_tucker": False,
    "lokr_use_scalar": False,
    "lokr_weight_decompose": True,
    "lokr_learning_rate": 1e-3,
    "lokr_train_epochs": 500,
    "lokr_train_batch_size": 1,
    "lokr_gradient_accumulation": 4,
    "lokr_save_every_n_epochs": 10,
    "lokr_training_shift": 3.0,
    "lokr_training_num_inference_steps": 8,
    "lokr_training_seed": 42,
    "lokr_output_dir": "./lokr_output",
    "lokr_export_path": "./lokr_output/final_lokr",
    "lokr_export_epoch": "Latest (auto)",
    "batch_input_folder": "",
    "batch_output_folder": "",
    "batch_auto_improve_lyrics": False,
    "batch_auto_improve_style": False,
    "ap_auto_postprocess": False,
    "ap_preserve_original": True,
    "ap_output_format": "wav",
    "ap_export_audio_only": False,
    "ap_trim_empty_output": False,
    "ap_trim_threshold_db": AUDIO_PROCESSING_DEFAULT_TRIM_THRESHOLD_DB,
    "ap_trim_margin_seconds": AUDIO_PROCESSING_DEFAULT_TRIM_MARGIN_SECONDS,
    "ap_trim_mincut": AUDIO_PROCESSING_DEFAULT_TRIM_MINCUT,
    "ap_trim_minclip": AUDIO_PROCESSING_DEFAULT_TRIM_MINCLIP,
    AUTO_EDITOR_WORKFLOW_EXPORT_KEY: AUTO_EDITOR_WORKFLOW_EXPORT_NONE,
    "ap_video_auto_quality": DEFAULT_VIDEO_AUTO_QUALITY,
    "ap_video_codec": DEFAULT_VIDEO_CODEC,
    "ap_video_bitrate": DEFAULT_VIDEO_BITRATE,
    "ap_video_crf": DEFAULT_VIDEO_CRF,
    "ap_video_preset": DEFAULT_VIDEO_PRESET,
    "ap_video_audio_codec": DEFAULT_VIDEO_AUDIO_CODEC,
    "ap_video_audio_bitrate": DEFAULT_VIDEO_AUDIO_BITRATE,
    "ap_diffpitcher_enabled": False,
    "ap_diffpitcher_mode": "template",
    "ap_diffpitcher_reference_audio": None,
    "ap_diffpitcher_midi": None,
    "ap_diffpitcher_steps": 50,
    "ap_diffpitcher_shift_semitones": 0.0,
    "ap_diffpitcher_mask_with_source": True,
    "ap_diffpitcher_device": "auto",
    "ap_builtin_preset": "Generic AI",
    "ap_run_subprocess": True,
    "ap_disable_upload_preview": False,
    **{f"ap_{key}_enabled": True for key in STAGE_KEYS},
    **{f"ap_{key}": DEFAULT_STAGE_VALUES[key] for key in STAGE_KEYS},
    "sam_auto_postprocess": False,
    "sam_preserve_original": True,
    "sam_trim_empty_output": False,
    "sam_trim_threshold_db": SAM_AUDIO_DEFAULT_TRIM_THRESHOLD_DB,
    "sam_output_format": "mp3",
    "sam_prompt_mode": "text",
    "sam_prompt_preset": ["vocals"],
    "sam_custom_prompt": "",
    "sam_batch_segment": False,
    "sam_use_span_anchor": False,
    "sam_anchor_json": "",
    "sam_anchor_polarity": "+",
    "sam_anchor_start": 0.0,
    "sam_anchor_end": 1.0,
    "sam_predict_spans": _DEFAULT_SAM_VRAM_VALUES["predict_spans"],
    "sam_reranking_candidates": _DEFAULT_SAM_VRAM_VALUES["reranking_candidates"],
    "sam_ranker_mode": _DEFAULT_SAM_VRAM_VALUES["ranker_mode"],
    "sam_ode_steps": _DEFAULT_SAM_VRAM_VALUES["ode_steps"],
    "sam_seed": 99,
    "sam_random_seed": False,
    "sam_vram_preset": _DEFAULT_SAM_VRAM_PRESET,
    "sam_quantization": _DEFAULT_SAM_VRAM_VALUES["quantization"],
    "sam_attention_backend": _DEFAULT_SAM_VRAM_VALUES["attention_backend"],
    "sam_device_mode": _DEFAULT_SAM_VRAM_VALUES["device_mode"],
    "sam_low_vram_lite": _DEFAULT_SAM_VRAM_VALUES["low_vram_lite"],
    "sam_chunked": _DEFAULT_SAM_VRAM_VALUES["chunked"],
    "sam_long_audio_mode": _DEFAULT_SAM_VRAM_VALUES["long_audio_mode"],
    "sam_chunk_seconds": _DEFAULT_SAM_VRAM_VALUES["chunk_seconds"],
    "sam_chunk_overlap_seconds": _DEFAULT_SAM_VRAM_VALUES["chunk_overlap_seconds"],
    "sam_subprocess": _DEFAULT_SAM_VRAM_VALUES["subprocess"],
    "sam_compile_model": False,
    "sam_unload_generation": True,
    "sam_include_residual": True,
    "sam_include_video": True,
    "sam_batch_input_folder": "",
    "sam_batch_output_folder": "",
    "sam_batch_recursive": False,
}
