"""Generation run event wiring helpers.

This module isolates the primary generation-button click chain that clears
outputs, runs batched generation, and schedules background pre-generation.
"""

from .. import results_handlers as res_h
from ..generation.cancel_actions import (
    CANCEL_CONFIRM_JS,
    request_generation_cancel_pair_from_ui,
)
from ...media_upload_values import latest_upload_path
from .context import GenerationWiringContext
from .audio_processing_wiring import audio_processing_generation_inputs
from .sam_audio_wiring import sam_audio_generation_inputs
from .inline_result_preview import (
    append_inline_result_preview,
    build_inline_result_outputs,
    prepare_inline_result_preview,
    sync_inline_result_preview,
)


def build_generation_run_inputs(generation_section, results_section):
    """Return ordered inputs for the generation wrapper."""

    return [
        generation_section["captions"],
        generation_section["lyrics"],
        generation_section["bpm"],
        generation_section["key_scale"],
        generation_section["time_signature"],
        generation_section["vocal_language"],
        generation_section["inference_steps"],
        generation_section["guidance_scale"],
        generation_section["random_seed_checkbox"],
        generation_section["seed"],
        generation_section["reference_audio"],
        generation_section["audio_duration"],
        generation_section["batch_size_input"],
        generation_section["src_audio"],
        generation_section["src_audio_preview"],
        generation_section["src_audio_preview_original"],
        generation_section["text2music_audio_code_string"],
        generation_section["repainting_start"],
        generation_section["repainting_end"],
        generation_section["instruction_display_gen"],
        generation_section["audio_cover_strength"],
        generation_section["cover_noise_strength"],
        generation_section["task_type"],
        generation_section["no_fsq"],
        generation_section["use_adg"],
        generation_section["cfg_interval_start"],
        generation_section["cfg_interval_end"],
        generation_section["shift"],
        generation_section["infer_method"],
        generation_section["sampler_mode"],
        generation_section["velocity_norm_threshold"],
        generation_section["velocity_ema_factor"],
        generation_section["dcw_enabled"],
        generation_section["dcw_mode"],
        generation_section["dcw_scaler"],
        generation_section["dcw_high_scaler"],
        generation_section["dcw_wavelet"],
        generation_section["custom_timesteps"],
        generation_section["audio_format"],
        generation_section["mp3_bitrate"],
        generation_section["mp3_sample_rate"],
        generation_section["lm_temperature"],
        generation_section["think_checkbox"],
        generation_section["lm_cfg_scale"],
        generation_section["lm_top_k"],
        generation_section["lm_top_p"],
        generation_section["lm_negative_prompt"],
        generation_section["use_cot_metas"],
        generation_section["use_cot_caption"],
        generation_section["use_cot_language"],
        results_section["is_format_caption_state"],
        generation_section["constrained_decoding_debug"],
        generation_section["allow_lm_batch"],
        generation_section["auto_score"],
        generation_section["auto_lrc"],
        generation_section["score_scale"],
        generation_section["lm_batch_chunk_size"],
        generation_section["track_name"],
        generation_section["extract_all_stems"],
        generation_section["complete_track_classes"],
        generation_section["enable_normalization"],
        generation_section["normalization_db"],
        generation_section["fade_in_duration"],
        generation_section["fade_out_duration"],
        generation_section["latent_shift"],
        generation_section["latent_rescale"],
        generation_section["repaint_mode"],
        generation_section["repaint_strength"],
        generation_section["retake_variance"],
        generation_section["retake_seed"],
        generation_section["flow_edit_morph"],
        generation_section["flow_edit_source_caption"],
        generation_section["flow_edit_source_lyrics"],
        generation_section["flow_edit_n_min"],
        generation_section["flow_edit_n_max"],
        generation_section["flow_edit_n_avg"],
        generation_section["autogen_checkbox"],
        results_section["current_batch_index"],
        results_section["total_batches"],
        results_section["batch_queue"],
        results_section["generation_params_state"],
        generation_section["subprocess_mode_checkbox"],
        generation_section["config_path"],
        generation_section["device"],
        generation_section["vae_checkpoint"],
        generation_section["lm_model_path"],
        generation_section["backend_dropdown"],
        generation_section["init_llm_checkbox"],
        generation_section["lm_use_legacy_cfg_prompt"],
        generation_section["use_flash_attention_checkbox"],
        generation_section["offload_to_cpu_checkbox"],
        generation_section["offload_dit_to_cpu_checkbox"],
        generation_section["compile_model_checkbox"],
        generation_section["quantization_checkbox"],
        generation_section["mlx_dit_checkbox"],
        generation_section["mlx_vae_chunk_size"],
        generation_section["lora_dropdown"],
        generation_section["lora_path"],
        generation_section["use_lora_checkbox"],
        generation_section["lora_scale_slider"],
        generation_section["generate_lm_audio_codes"],
        generation_section["extract_trim_empty_output"],
        generation_section["extract_trim_threshold_db"],
        generation_section["extract_output_format"],
        generation_section["instrumental_checkbox"],
        generation_section["repaint_dont_switch_with_lyrics"],
        *audio_processing_generation_inputs(generation_section),
        *sam_audio_generation_inputs(generation_section),
    ]


def _with_effective_reference_preview(args):
    """Replace reference audio with the edited preview from an extra tail input."""

    if not args:
        return args
    reference_preview = args[-1]
    forwarded_args = list(args[:-1])
    reference_preview_path = latest_upload_path(reference_preview)
    if reference_preview_path and len(forwarded_args) > 10:
        forwarded_args[10] = reference_preview_path
    return tuple(forwarded_args)


def build_generation_run_outputs(generation_section, results_section):
    """Return ordered outputs for the generation wrapper."""

    return [
        results_section["generated_audio_1"],
        results_section["generated_audio_2"],
        results_section["generated_audio_3"],
        results_section["generated_audio_4"],
        results_section["generated_audio_5"],
        results_section["generated_audio_6"],
        results_section["generated_audio_7"],
        results_section["generated_audio_8"],
        results_section["original_audio_1"],
        results_section["original_audio_2"],
        results_section["original_audio_3"],
        results_section["original_audio_4"],
        results_section["original_audio_5"],
        results_section["original_audio_6"],
        results_section["original_audio_7"],
        results_section["original_audio_8"],
        results_section["generated_audio_batch"],
        results_section["generation_info"],
        results_section["status_output"],
        generation_section["seed"],
        results_section["score_display_1"],
        results_section["score_display_2"],
        results_section["score_display_3"],
        results_section["score_display_4"],
        results_section["score_display_5"],
        results_section["score_display_6"],
        results_section["score_display_7"],
        results_section["score_display_8"],
        results_section["codes_display_1"],
        results_section["codes_display_2"],
        results_section["codes_display_3"],
        results_section["codes_display_4"],
        results_section["codes_display_5"],
        results_section["codes_display_6"],
        results_section["codes_display_7"],
        results_section["codes_display_8"],
        results_section["details_accordion_1"],
        results_section["details_accordion_2"],
        results_section["details_accordion_3"],
        results_section["details_accordion_4"],
        results_section["details_accordion_5"],
        results_section["details_accordion_6"],
        results_section["details_accordion_7"],
        results_section["details_accordion_8"],
        results_section["lrc_display_1"],
        results_section["lrc_display_2"],
        results_section["lrc_display_3"],
        results_section["lrc_display_4"],
        results_section["lrc_display_5"],
        results_section["lrc_display_6"],
        results_section["lrc_display_7"],
        results_section["lrc_display_8"],
        results_section["lm_metadata_state"],
        results_section["is_format_caption_state"],
        results_section["current_batch_index"],
        results_section["total_batches"],
        results_section["batch_queue"],
        results_section["generation_params_state"],
        results_section["batch_indicator"],
        results_section["prev_batch_btn"],
        results_section["next_batch_btn"],
        results_section["next_batch_status"],
        results_section["restore_params_btn"],
    ]


def build_clear_audio_outputs(results_section):
    """Return ordered audio outputs cleared before generation."""

    return [
        results_section["generated_audio_1"],
        results_section["generated_audio_2"],
        results_section["generated_audio_3"],
        results_section["generated_audio_4"],
        results_section["generated_audio_5"],
        results_section["generated_audio_6"],
        results_section["generated_audio_7"],
        results_section["generated_audio_8"],
        results_section["original_audio_1"],
        results_section["original_audio_2"],
        results_section["original_audio_3"],
        results_section["original_audio_4"],
        results_section["original_audio_5"],
        results_section["original_audio_6"],
        results_section["original_audio_7"],
        results_section["original_audio_8"],
        results_section["generated_audio_batch"],
    ]


def register_generation_run_handlers(context: GenerationWiringContext) -> None:
    """Register batched generation-run event wiring for audio inference.

    Args:
        context (GenerationWiringContext): Shared wiring context used by
        `register_generation_run_handlers`; reads `generation_section`,
        `results_section`, `dit_handler`, and `llm_handler` to bind the
        generate-button click chain.

    Returns:
        None: Registers click/then handlers in-place on generation components.
    """

    generation_section = context.generation_section
    results_section = context.results_section
    dit_handler = context.dit_handler
    llm_handler = context.llm_handler

    def generation_wrapper(*args):
        """Stream generation outputs and mirror status into the inline preview.

        Args:
            *args (Any): Positional passthrough inputs forwarded unchanged to
                `res_h.generate_with_batch_management(dit_handler, llm_handler, *args)`.

        Yields:
            Any: Streamed generation updates with inline preview updates appended.

        Raises:
            Exception: Propagates exceptions raised by
            `res_h.generate_with_batch_management`.
        """

        forwarded_args = _with_effective_reference_preview(args)
        for outputs in res_h.generate_with_batch_management(
            dit_handler,
            llm_handler,
            *forwarded_args,
        ):
            yield append_inline_result_preview(outputs)

    generation_section["generate_btn"].click(
        fn=res_h.clear_audio_outputs_for_new_generation,
        outputs=[
            results_section["generated_audio_1"],
            results_section["generated_audio_2"],
            results_section["generated_audio_3"],
            results_section["generated_audio_4"],
            results_section["generated_audio_5"],
            results_section["generated_audio_6"],
            results_section["generated_audio_7"],
            results_section["generated_audio_8"],
            results_section["original_audio_1"],
            results_section["original_audio_2"],
            results_section["original_audio_3"],
            results_section["original_audio_4"],
            results_section["original_audio_5"],
            results_section["original_audio_6"],
            results_section["original_audio_7"],
            results_section["original_audio_8"],
            results_section["generated_audio_batch"],
        ],
    ).then(
        fn=prepare_inline_result_preview,
        inputs=[generation_section["task_type"]],
        outputs=build_inline_result_outputs(generation_section),
    ).then(
        fn=generation_wrapper,
        inputs=[
            generation_section["captions"],
            generation_section["lyrics"],
            generation_section["bpm"],
            generation_section["key_scale"],
            generation_section["time_signature"],
            generation_section["vocal_language"],
            generation_section["inference_steps"],
            generation_section["guidance_scale"],
            generation_section["random_seed_checkbox"],
            generation_section["seed"],
            generation_section["reference_audio"],
            generation_section["audio_duration"],
            generation_section["batch_size_input"],
            generation_section["src_audio"],
            generation_section["src_audio_preview"],
            generation_section["src_audio_preview_original"],
            generation_section["text2music_audio_code_string"],
            generation_section["repainting_start"],
            generation_section["repainting_end"],
            generation_section["instruction_display_gen"],
            generation_section["audio_cover_strength"],
            generation_section["cover_noise_strength"],
            generation_section["task_type"],
            generation_section["no_fsq"],
            generation_section["use_adg"],
            generation_section["cfg_interval_start"],
            generation_section["cfg_interval_end"],
            generation_section["shift"],
            generation_section["infer_method"],
            generation_section["sampler_mode"],
            generation_section["velocity_norm_threshold"],
            generation_section["velocity_ema_factor"],
            generation_section["dcw_enabled"],
            generation_section["dcw_mode"],
            generation_section["dcw_scaler"],
            generation_section["dcw_high_scaler"],
            generation_section["dcw_wavelet"],
            generation_section["custom_timesteps"],
            generation_section["audio_format"],
            generation_section["mp3_bitrate"],
            generation_section["mp3_sample_rate"],
            generation_section["lm_temperature"],
            generation_section["think_checkbox"],
            generation_section["lm_cfg_scale"],
            generation_section["lm_top_k"],
            generation_section["lm_top_p"],
            generation_section["lm_negative_prompt"],
            generation_section["use_cot_metas"],
            generation_section["use_cot_caption"],
            generation_section["use_cot_language"],
            results_section["is_format_caption_state"],
            generation_section["constrained_decoding_debug"],
            generation_section["allow_lm_batch"],
            generation_section["auto_score"],
            generation_section["auto_lrc"],
            generation_section["score_scale"],
            generation_section["lm_batch_chunk_size"],
            generation_section["track_name"],
            generation_section["extract_all_stems"],
            generation_section["complete_track_classes"],
            generation_section["enable_normalization"],
            generation_section["normalization_db"],
            generation_section["fade_in_duration"],
            generation_section["fade_out_duration"],
            generation_section["latent_shift"],
            generation_section["latent_rescale"],
            generation_section["repaint_mode"],
            generation_section["repaint_strength"],
            generation_section["retake_variance"],
            generation_section["retake_seed"],
            generation_section["flow_edit_morph"],
            generation_section["flow_edit_source_caption"],
            generation_section["flow_edit_source_lyrics"],
            generation_section["flow_edit_n_min"],
            generation_section["flow_edit_n_max"],
            generation_section["flow_edit_n_avg"],
            generation_section["autogen_checkbox"],
            results_section["current_batch_index"],
            results_section["total_batches"],
            results_section["batch_queue"],
            results_section["generation_params_state"],
            generation_section["subprocess_mode_checkbox"],
            generation_section["config_path"],
            generation_section["device"],
            generation_section["vae_checkpoint"],
            generation_section["lm_model_path"],
            generation_section["backend_dropdown"],
            generation_section["init_llm_checkbox"],
            generation_section["lm_use_legacy_cfg_prompt"],
            generation_section["use_flash_attention_checkbox"],
            generation_section["offload_to_cpu_checkbox"],
            generation_section["offload_dit_to_cpu_checkbox"],
            generation_section["compile_model_checkbox"],
            generation_section["quantization_checkbox"],
            generation_section["mlx_dit_checkbox"],
            generation_section["mlx_vae_chunk_size"],
            generation_section["lora_dropdown"],
            generation_section["lora_path"],
            generation_section["use_lora_checkbox"],
            generation_section["lora_scale_slider"],
            generation_section["generate_lm_audio_codes"],
            generation_section["extract_trim_empty_output"],
            generation_section["extract_trim_threshold_db"],
            generation_section["extract_output_format"],
            generation_section["instrumental_checkbox"],
            generation_section["repaint_dont_switch_with_lyrics"],
            *audio_processing_generation_inputs(generation_section),
            *sam_audio_generation_inputs(generation_section),
            generation_section["reference_audio_preview"],
        ],
        outputs=[
            results_section["generated_audio_1"],
            results_section["generated_audio_2"],
            results_section["generated_audio_3"],
            results_section["generated_audio_4"],
            results_section["generated_audio_5"],
            results_section["generated_audio_6"],
            results_section["generated_audio_7"],
            results_section["generated_audio_8"],
            results_section["original_audio_1"],
            results_section["original_audio_2"],
            results_section["original_audio_3"],
            results_section["original_audio_4"],
            results_section["original_audio_5"],
            results_section["original_audio_6"],
            results_section["original_audio_7"],
            results_section["original_audio_8"],
            results_section["generated_audio_batch"],
            results_section["generation_info"],
            results_section["status_output"],
            generation_section["seed"],
            results_section["score_display_1"],
            results_section["score_display_2"],
            results_section["score_display_3"],
            results_section["score_display_4"],
            results_section["score_display_5"],
            results_section["score_display_6"],
            results_section["score_display_7"],
            results_section["score_display_8"],
            results_section["codes_display_1"],
            results_section["codes_display_2"],
            results_section["codes_display_3"],
            results_section["codes_display_4"],
            results_section["codes_display_5"],
            results_section["codes_display_6"],
            results_section["codes_display_7"],
            results_section["codes_display_8"],
            results_section["details_accordion_1"],
            results_section["details_accordion_2"],
            results_section["details_accordion_3"],
            results_section["details_accordion_4"],
            results_section["details_accordion_5"],
            results_section["details_accordion_6"],
            results_section["details_accordion_7"],
            results_section["details_accordion_8"],
            results_section["lrc_display_1"],
            results_section["lrc_display_2"],
            results_section["lrc_display_3"],
            results_section["lrc_display_4"],
            results_section["lrc_display_5"],
            results_section["lrc_display_6"],
            results_section["lrc_display_7"],
            results_section["lrc_display_8"],
            results_section["lm_metadata_state"],
            results_section["is_format_caption_state"],
            results_section["current_batch_index"],
            results_section["total_batches"],
            results_section["batch_queue"],
            results_section["generation_params_state"],
            results_section["batch_indicator"],
            results_section["prev_batch_btn"],
            results_section["next_batch_btn"],
            results_section["next_batch_status"],
            results_section["restore_params_btn"],
            *build_inline_result_outputs(generation_section),
        ],
    ).then(
        fn=sync_inline_result_preview,
        inputs=[
            results_section["generated_audio_1"],
            results_section["generated_audio_batch"],
            results_section["status_output"],
        ],
        outputs=build_inline_result_outputs(generation_section),
    ).then(
        fn=lambda *args: res_h.generate_next_batch_background(dit_handler, llm_handler, *args),
        inputs=[
            generation_section["autogen_checkbox"],
            results_section["generation_params_state"],
            results_section["current_batch_index"],
            results_section["total_batches"],
            results_section["batch_queue"],
            results_section["is_format_caption_state"],
        ],
        outputs=[
            results_section["batch_queue"],
            results_section["total_batches"],
            results_section["next_batch_status"],
            results_section["next_batch_btn"],
        ],
    )
    cancel_event = generation_section["cancel_generation_btn"].click(
        fn=None,
        inputs=None,
        outputs=[generation_section["cancel_confirmed_state"]],
        js=CANCEL_CONFIRM_JS,
        queue=False,
        show_progress="hidden",
    )
    cancel_event.then(
        fn=request_generation_cancel_pair_from_ui,
        inputs=[
            generation_section["cancel_confirmed_state"],
            generation_section["subprocess_mode_checkbox"],
        ],
        outputs=[
            results_section["status_output"],
            generation_section["inline_generation_status"],
        ],
        queue=False,
        show_progress="hidden",
    )
